language: node_js
os:
  - windows
  - linux
  - osx
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt update && apt install x11-xserver-utils; fi
script:
  - npm run lint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run npm test; else npm test; fi
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
